/**
 * This file is a configuration file generated by the `Template` extension on `vscode`
 * @see https://marketplace.visualstudio.com/items?itemName=yongwoo.template
 */
module.exports = {
  // You can change the template path to another path
  templateRootPath: "./.templates",
  // After copying the template file the `replaceFileTextFn` function is executed
  replaceFileTextFn: (fileText, templateName, utils) => {
    // @see https://www.npmjs.com/package/change-case
    const { changeCase } = utils;
    const withoutExtension = templateName.split(".")[0];
    // You can change the text in the file
    const replace = fileText
      .replace(/__templateName__/g, withoutExtension)
      .replace(
        /__templateNameToPascalCase__/g,
        changeCase.pascalCase(withoutExtension)
      )
      .replace(
        /__templateNameToParamCase__/g,
        changeCase.paramCase(withoutExtension)
      ).replace(
        /__templateNameToCamelCase__/g,
        changeCase.camelCase(withoutExtension)
      )
    // camale case

    return replace;
  },
  renameFileFn: (fileName, templateName, utils) => {
    const { path } = utils;
    const { base } = path.parse(fileName);
    return base.replace(/__templateName__/gm, templateName);
  },
  renameSubDirectoriesFn: (directoryName, templateName, _utils) => {
    const { changeCase } = _utils;
    const newDirectoryName = changeCase.paramCase(templateName);
    return directoryName.replace(/__templateName__/g, newDirectoryName);
  }
};
